runtime: go113

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/.*
  secure: always
  redirect_http_response_code: 301

- url: /static
  static_dir: static
  secure: always
  redirect_http_response_code: 301

- url: .*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
